config/routes.rb
Rails.application.routes.draw do
  root "application#homepage"
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get 'reviews/recent_reviews', to: 'reviews#recent_reviews'
  get 'popular_books', to: 'reviews#popular_books'

  resources :users, only: [:show, :delete] do
      resources :reviews
  end

  resources :books do
    resources :reviews
  end

get '/auth/facebook/callback' => 'sessions#oauth'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :reviews
  has_many :users, through: :reviews

  default_scope -> { order(id: :asc) }


  def reviews_attributes=(reviews_attributes)
    reviews_attributes.values.each do |reviews_attributes|
      self.reviews.build(reviews_attributes)
    end
  end

  validates :title, :author, presence: true
  validates :title, uniqueness: true

  def next
    books = book_ids_by_title
    book_index = books.find_index(id)
    next_book = book_index + 1
    if next_book < books.length
      books[next_book]
    else
      id
    end
  end

  def prev
    books = book_ids_by_title
    book_index = books.find_index(id)
    prev_book = book_index - 1
    if prev_book > 0
      books[prev_book]
    else
      id
    end
  end

private

def book_ids_by_title
  @book_ids ||= Book.order(title: :asc).pluck(:id)
end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :book

  default_scope -> { order(created_at: :desc) }

  scope :recent_reviews, -> { order(created_at: :desc) }

  def self.highest_rated_books
    @highest_reviews = self.all.select do |r|
      r.rating == 5
    end
    @highest_reviews.map do |review|
      review.book
    end.uniq
  end

  def self.highest_level
      @most_severe_vibes = self.all.select do |sv|
        sv.level == 5
      end
      @most_severe_vibes.map do |vibe|
        vibe.name
      end.uniq
    end


  validates :title, :content, presence: true
  validates :content, length: { maximum: 250 }
  validates :rating, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :books, through: :reviews
  has_many :reviews

  validates :username, presence: true, length: { maximum: 15}, uniqueness: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 20},
  format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.most_reviews
    self.all.sort_by {|user| user.reviews.size * -1} [0]
  end

  def self.find_or_create_by_omniauth(auth_hash)
    where(email: auth_hash[:info][:email]).first_or_create do |user|
      user.username = auth_hash[:info][:name]
      user.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def homepage
    if logged_in?
      redirect_to user_path(current_user)
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
    redirect_to '/', notice: 'You are logged out!'
  end

 end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    @book.reviews.build(params[:reviews_attributes])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path(@book)
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    @review = @book.reviews.build
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @book.to_json }
    end
  end

private

  def book_params
    params.require(:book).permit(:title, :author, :summary, reviews_attributes: [:title, :content, :rating, :user_id])
  end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  def new #user creates new review
    #needs to be logged in
    #validations
    #redirects to book show page with new review
  end

  def create
    #submits new review form
  end

  def edit
    #user can comment their own review
  end

  def update
    #updates reviews if edited
  end

  def delete
    #user can delete their own review
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    validate_login
  end

  def oauth
    user = User.find_or_create_by_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    log_out
  end

protected

  def auth
    request.env['omniauth.auth']
  end

  private

  def session_params
    params.require(:user).permit(:username, :email, :password_confirmation, :uid, :password)
  end

  def validate_login
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render :new
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
      flash[:success] = "You're all signed up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :uid)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/homepage.html.erb
<div class="center jumbotron">

  <h1>Welcome to BookClub</h1>

  <h4>
    Where you can find the next book to get lost in
  </h4>

  <br>
  <br>

  <%= link_to "Log In", login_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-primary" %>
  <br>
  - or -
  <br>
  <%= link_to 'Log in with Facebook!', '/auth/facebook', class: "btn btn-lg btn-primary" %>

  <br>
  <br>

<center><%= image_tag("books2.jpg", alt: "Books logo") %>

</div>

app/views/books/index.html.erb
<h1>All Books</h1>


<% @books.each do |book| %>
<ul>
  <li><h4><b><%= link_to book.title, book_path(book) %></h4>By:</b> <%= book.author %></li>
</ul>
<% end %>

<% if logged_in? %>
<br><%= link_to "Add New Book", new_book_path, class: "btn btn-lg btn-primary"  %>
<% end %>

app/views/books/new.html.erb
<h1>Add a new book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">


    <%= form_for @book do |book_form| %>

    <%= render 'shared/error_messages', object: book_form.object %>


          <%= book_form.label :title %>
          <%= book_form.text_field :title, class: 'form-control' %>

          <%= book_form.label :author %>
          <%= book_form.text_field :author, class: 'form-control' %>

          <%= book_form.label :summary %>
          <%= book_form.text_area :summary %>


            <%= book_form.fields_for :reviews, @book.reviews.build do |rev_form| %>

            <%= rev_form.label :title %>
            <%= rev_form.text_field :title %>

            <%= rev_form.label :content %>
            <%= rev_form.text_area :content %>

            <%= rev_form.label :rating %> (1-5)
            <%= rev_form.number_field :rating %>

            <%= rev_form.hidden_field :user_id, value: current_user.id %>

            <% end %>

          <%= book_form.submit %>

    <% end %>

  </div>
</div>

app/views/books/show.html.erb
<center><h1 class="bookTitle"><%=@book.title.titleize%></h1><br>
By: <h3 class="bookAuthor"><%=@book.author.titleize%></h3><br>
<p>Summary:<h5 class="bookSummary"><%=@book.summary%></h5><br></p></center>
<br>
<br>
<br>
<center>
<%= link_to "Prev Book", book_path(@book.prev), :class => "previous_link", :"data-attribute" => @book.id %>
<%= link_to "Next Book", book_path(@book.next), :class => "next_link", :"data-attribute" => @book.id  %>
</center>

<h3>Reviews:</h3>


<%= link_to "Load reviews", book_reviews_path(@book), :class => "reviews_link" %>
<br>
<div>
  <ol class="reviews">
    <!-- this is where the reviews will be inserted via ajax/jquery -->
  </ol>
</div>
<br>
<br>
<div class="review_form">
<% if logged_in? %>
  <%= render 'reviews/form' %>
<% end %>
</div>
<br>


<!-- # <% if logged_in? %>
# <%= link_to "Add A Review", new_book_review_path(@book), class: "btn btn-lg btn-primary" %>
# <% end %> -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    @RailsProject
    by Aysan
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <% if !logged_in? %>
        <li><%= link_to "Home", root_path %></li>
        <% end %>
        <li><%= link_to "Books", books_path %></li>
        <li><%= link_to "Recent Reviews", reviews_recent_reviews_path %></li>
        <li><%= link_to "Popular Book", popular_books_path %></li>

      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :destroy %></li>
        <% end %>
      </ul>
    </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1><%= @book.title %></h1>
<h2>Edit Review</h2>
<%= form_for [@book, @review]  do |book_review| %>

  <%= render 'shared/error_messages', object: book_review.object %>

      <%= book_review.label :title %>
      <%= book_review.text_field :title, class: 'form-control' %>

      <%= book_review.label :content %>
      <%= book_review.text_area :content, class: 'form-control' %>

      <%= book_review.label :rating %> (1-5)
      <%= book_review.number_field :rating, class: 'form-control' %>

      <%= book_review.submit "Submit", class: "btn btn-primary" %>

<% end %>

app/views/reviews/index.html.erb
<div id="list_reviews">
  <ol>
    <li>
      <% @reviews.each do |review| %>
        <b>Title:</b> <%= review.title %><br>
        <b>Review:</b> <%= review.content %><br>
        <b>Rating:</b> <%= review.rating %><br>
        <b>By:</b> <%= link_to review.user.username, user_path(review.user) %><br>
        <b>Posted:</b> <%= review.created_at %><br>
        <br>
        <br>
      <% end %>
    </li>
  </ol>

</div>

app/views/reviews/new.html.erb
<h1>Leave a Review!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
</div>

app/views/reviews/popular_books.html.erb
<h1>Popular Books</h1>

<center><% @popular_books.each do |book| %>
<ul>
  <b><%= link_to book.title, book_path(book) %> </b>
</ul>
<% end %>

app/views/reviews/recent_reviews.html.erb
<h1>Recent Reviews</h1>

<% @recent_reviews.each do |review| %>
<ul>
  <h4><li>Book: <%= link_to review.book.title, book_path(review.book) %></li></h4>
  <b>Title:</b> <%= review.title %><br>
  <b>Content:</b> <%= review.content %><br>
  <b>Posted:</b> <%= review.created_at %><br>
  <b>By:</b> <%= link_to review.user.username, user_path(review.user) %>
</ul>

<% end %>

app/views/reviews/show.html.erb
<% @book.reviews.each do |review| %>
  <b>Title:</b> <%= review.title %><br>
  <b>Review:</b> <%= review.content %><br>
  <b>Rating:</b> <%= review.rating %><br>
  <b>By:</b> <%= link_to review.user.username, user_path(review.user) %><br>
  <b>Posted:</b> <%= review.created_at %><br>
  <br>
  <br>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit "Create my account", class: "btn btn-primary" %>

<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username.titleize %>'s Profile</h1>

<div class="col-md-8">

  <h3> Reviews: (<%= @user.reviews.count %>)</h3>

      <% @user.reviews.each.with_index(1) do |review, i| %>
      <%= "#{i}" %>. <b>Book:</b> <%= link_to review.book.title, book_path(review.book) %><br>
        <ul>
          <li><b>Review:</b> <%= review.title %> - <%= review.content %> - <%= review.rating %><br></li>
            Posted: <%= review.created_at %><br>
        </ul>
        <% if current_user == review.user %>
        <%= link_to "edit", edit_user_review_path(current_user, review)  %> -
        <%= link_to "delete", user_review_path(current_user, review), method: :delete, data: { confirm: "You sure?" } %><br>
        <br>
        <br>
        <% end %>
      <% end %>

  </div>
</div>